// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pinabsakzzjcnkyoenpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpbmFic2FrenpqY25reW9lbnBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3Nzc5MjksImV4cCI6MjA5NTM1MzkyOX0.UuDQV04y_jfQD6dR3cVumolu2jq5h-w0JLLua80qSC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});