// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkbeoqskfeyqtyjtpufj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprYmVvcXNrZmV5cXR5anRwdWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODMyMjAsImV4cCI6MjA2OTQ1OTIyMH0.T__h5xs4QS2s5TAlQLc2i-ZNTUzJN7kwyOIgtuNTsV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});